### ISSUE TITLE
Several suggestions

### ISSUE THREAD

**Issue by HebaruSan** [willwill2will54/Flag-Pack#1]
This is an impressive collection! It inspired me to look for a few more that I consider fun or interesting.

Note, I have not checked the copyright status of any of these images. They may or may not be usable, but alternatives are easy to find via Google Image Search.

## The Elon Tesla Plaque

Very topical for KSP fans

![Elon](https://i.redd.it/5qm77uhnkxe01.jpg)

## Apollo 11

![Apollo](http://www.space-boosters.co.uk/ekmps/shops/spaceboosters/images/nasa-apollo-11-embroidered-4-mission-patch-yellow-border-2042-p.jpg)

## Space Shuttle

![Shuttle](https://upload.wikimedia.org/wikipedia/commons/5/5c/Shuttle_Patch.svg)

## Hubble Space Telescope

![Hubble](http://blog.signalnoise.com/wp-content/uploads/2011/08/i_nasa3.jpg)

### House Liao

![Liao](https://steamuserimages-a.akamaihd.net/ugc/848214756092180582/D06E0E9757D2009B5690488A52BED7ABEB08178E/)

### House Steiner

![Steiner](https://steamuserimages-a.akamaihd.net/ugc/848214756091810575/D8C7807B06499B0A973BF02620A07BD1C9275D98/)

### House Davion

![Davion](https://steamuserimages-a.akamaihd.net/ugc/848214756092107238/E35DF9C0BE7A999C7B9F587B5A6D741604795A4F/)

### House Marik

![Marik](https://steamuserimages-a.akamaihd.net/ugc/848214756092151376/BCE50DCB39EE1DE9FACDA7FFED7636F6C7298AB3/)

### House Kurita

![Kurita](https://steamuserimages-a.akamaihd.net/ugc/848214756092381293/CC905AF294A4EF708A4D321DFB978E805395A037/)

## Ben Franklin's pro-Union cartoon

![Franklin](https://upload.wikimedia.org/wikipedia/commons/9/9c/Benjamin_Franklin_-_Join_or_Die.jpg)

## Gadsden

![Gadsden](https://upload.wikimedia.org/wikipedia/commons/d/d8/Gadsden_flag.svg)

## Texas

To balance out California?

![Texas](https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg)

## Chicago, Illinois

Probably the flag most beloved by its residents

![Chicago](https://99percentinvisible.org/app/uploads/2010/10/Chicago-muni-flag.png)

## Madison, Wisconsin

Clearly aping Chicago

![Madison](https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Madison%2C_Wisconsin.svg)

## Prussia

As seen in the Napoleonic Wars

![Prussia](https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Prussia_%281892-1918%29.svg)

## Roman Empire

Senātus Populusque Rōmānus

![Roman](http://media.moddb.com/cache/images/mods/1/26/25785/thumb_620x2000/Roman_empire_flag.1.jpg)

## Vatican

![Vatican](https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_the_Vatican_City.svg)

## Anarchist

![Anarchist](https://upload.wikimedia.org/wikipedia/commons/d/d3/Anarchist_flag.svg)

## Communist Party USA

I always liked the half gear

![CPUSA](https://upload.wikimedia.org/wikipedia/commons/c/c6/Cpusa-flag-e1470730009543.png)

## Palestine

Because you've already got the other one

![Palestine](https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Palestine.svg)

## Worst flags

You've already got Provo, why not the other two notorious worst flags?

![Milwaukee](https://qph.fs.quoracdn.net/main-qimg-0f121c1c9c641d31940176edb69c4d2a.webp)

![Pocatello](https://qph.fs.quoracdn.net/main-qimg-01fb6c0aa3f1955ff24245c3c819e169.webp)

... although I'd understand if you felt the copyright notice made that last one too risky.

**Comment by willwill2will54** [comment]
@HebaruSan, Flags: integrated. Your last two flags didn't show up, for some reason, but I would be happy to look at them if you would... re-post (that doesn't seem like correct nomenclature) and I will perhaps put them in the next release. Still, with FlagPack now into the second release, and with a bit of your own graft invested into it, would you mind reviewing my netKAN PR [here](https://github.com/KSP-CKAN/NetKAN/pull/6557).
