### ISSUE TITLE
__MACOSX folder and .DS_Store files in download

### ISSUE THREAD

**Issue by HebaruSan** [willwill2will54/Flag-Pack#2]
The ZIP download for this mod includes a `__MACOSX` folder at the top level and `.DS_Store` files, which are extra data that MacOSX puts in folders for its own purposes:

![image](https://user-images.githubusercontent.com/1559108/42302256-7798dbd2-8009-11e8-8417-195929bbf662.png)

![image](https://user-images.githubusercontent.com/1559108/42302328-d6370d30-8009-11e8-80de-845fc4f9b1dd.png)

These files are not needed for the mod to function, so they represent extra download bandwidth and space on disk consumed unnecessarily. I'd recommend removing them.

Discovered while investigating KSP-CKAN/CKAN#2467.

**Comment by willwill2will54** [comment]
fixed in 1.1.1
