### ISSUE TITLE
Files with names that are invalid on Windows

### ISSUE THREAD

**Issue by HebaruSan** [willwill2will54/Flag-Pack#3]
If you try to install this mod on Windows, the extract process fails:

![image](https://user-images.githubusercontent.com/1559108/42302138-d9076fd8-8008-11e8-8621-aea052b685ad.png)

This appears to be because it's not valid to have quotes in file names:

![image](https://user-images.githubusercontent.com/1559108/42302367-0a5c6eac-800a-11e8-8f8e-5c88a15e860f.png)

This also causes problems installing from CKAN.
Discovered while investigating KSP-CKAN/CKAN#2467.

**Comment by willwill2will54** [comment]
Thanks for bringing it to my attention. Working on it.

**Comment by willwill2will54** [comment]
Fixed in 1.1.1.
